# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proxyx < Formula
  desc "ProxyX Reverse Proxy Service"
  homepage "https://github.com/otabek05/proxyx"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/otabek05/ProxyX/releases/download/v0.1.1/proxyx_0.1.1_darwin_amd64.tar.gz"
      sha256 "8f684d38df6b3da84e85259fda6662e75895ba52262aaed1cf5cd961c0ef1f19"

      def install
        bin.install "proxyx"
        (etc/"proxyx").install "web"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/otabek05/ProxyX/releases/download/v0.1.1/proxyx_0.1.1_darwin_arm64.tar.gz"
      sha256 "63c50276fde76f075f9c3f916dc4f890cc71e10fd60ebc6c4b61f5d3e211bfc5"

      def install
        bin.install "proxyx"
        (etc/"proxyx").install "web"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/otabek05/ProxyX/releases/download/v0.1.1/proxyx_0.1.1_linux_amd64.tar.gz"
      sha256 "9d25cfae847116371d8315615edebd4a12755c4357e24ac8e4139ffcf63e5878"
      def install
        bin.install "proxyx"
        (etc/"proxyx").install "web"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/otabek05/ProxyX/releases/download/v0.1.1/proxyx_0.1.1_linux_arm64.tar.gz"
      sha256 "b97872ecf1bc70a761ae488ffa4bb587c3019930f32a9c30d041517175db1285"
      def install
        bin.install "proxyx"
        (etc/"proxyx").install "web"
      end
    end
  end
end
