# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proxyx < Formula
  desc "ProxyX Reverse Proxy Service"
  homepage "https://github.com/otabek05/proxyx"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/otabek05/ProxyX/releases/download/v0.1.0/proxyx_0.1.0_darwin_amd64.tar.gz"
      sha256 "96ec344609f091a68bebe91b0e042eece65c8ef07d29d068f00a389d001ad086"

      def install
        bin.install "proxyx"
        etc.install Dir["web"] => "proxyx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/otabek05/ProxyX/releases/download/v0.1.0/proxyx_0.1.0_darwin_arm64.tar.gz"
      sha256 "75089456a97f0ab6b3ed775d5e23f8324a895763ee565e7829b0cdcc4e6af9f6"

      def install
        bin.install "proxyx"
        etc.install Dir["web"] => "proxyx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/otabek05/ProxyX/releases/download/v0.1.0/proxyx_0.1.0_linux_amd64.tar.gz"
      sha256 "00d94d310781b19d03b1d1f56046781bdacc8937cbf474bfa8fca6e9a43baf6d"
      def install
        bin.install "proxyx"
        etc.install Dir["web"] => "proxyx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/otabek05/ProxyX/releases/download/v0.1.0/proxyx_0.1.0_linux_arm64.tar.gz"
      sha256 "b0f41b2e5ed7da7640d1653eab944e2fc4f471e7e23c389d6681ac7a6d886793"
      def install
        bin.install "proxyx"
        etc.install Dir["web"] => "proxyx"
      end
    end
  end

  def post_install
    system "sh", "-e", "-c", <<~'EOS'
      mkdir -p "#{etc}/proxyx"
      if [ -d "#{etc}/proxyx/web" ]; then
        cp -R "#{etc}/proxyx/web/"* "#{etc}/proxyx/" || true
        rm -rf "#{etc}/proxyx/web"
      fi
    EOS
  end
end
