# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proxyx < Formula
  desc "ProxyX Reverse Proxy Service"
  homepage "https://github.com/otabek05/proxyx"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/otabek05/ProxyX/releases/download/v0.2.0/proxyx_0.2.0_darwin_amd64.tar.gz"
      sha256 "b73607c8895fb6b66cc2b3ca498b82628f853d4ddb09fdb00b0bdcc51d2b6bc5"

      def install
        bin.install "proxyx"
        etc.install Dir["web"] => "proxyx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/otabek05/ProxyX/releases/download/v0.2.0/proxyx_0.2.0_darwin_arm64.tar.gz"
      sha256 "70f3753c915b5be8441f4caf6bcf1a9efc9fe828a2baaf7d47b96d37d5495f63"

      def install
        bin.install "proxyx"
        etc.install Dir["web"] => "proxyx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/otabek05/ProxyX/releases/download/v0.2.0/proxyx_0.2.0_linux_amd64.tar.gz"
      sha256 "8b986bea24f5d5be0b2761afb977ca166e2d2ef47f5d3158bb3ea88e6b13e252"
      def install
        bin.install "proxyx"
        etc.install Dir["web"] => "proxyx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/otabek05/ProxyX/releases/download/v0.2.0/proxyx_0.2.0_linux_arm64.tar.gz"
      sha256 "e955f38a53cd1914df61e107773342041cddd94baa618ef95f0cb78996db4ab5"
      def install
        bin.install "proxyx"
        etc.install Dir["web"] => "proxyx"
      end
    end
  end

  def post_install
    system "sh", "-e", "-c", <<~'EOS'
      mkdir -p "#{etc}/proxyx"
      if [ -d "#{etc}/proxyx/web" ]; then
        cp -R "#{etc}/proxyx/web/"* "#{etc}/proxyx/" || true
        rm -rf "#{etc}/proxyx/web"
      fi
    EOS
  end
end
